services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: postgres
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    ports:
      - "1337:1337"
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - strapi-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d strapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - strapi-network

volumes:
  postgres_data:

networks:
  strapi-network: